<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE qalab [<!ELEMENT qalab (summary,file*)>
<!ATTLIST qalab version CDATA #REQUIRED>
<!ELEMENT summary (summaryresult*)>
<!ELEMENT file (result+)>
<!ATTLIST file id ID #REQUIRED>
<!ATTLIST file project CDATA #REQUIRED>
<!ATTLIST file module CDATA #REQUIRED>
<!ATTLIST file path CDATA #REQUIRED>
<!ELEMENT result EMPTY>
<!ATTLIST result date CDATA #REQUIRED>
<!ATTLIST result statvalue CDATA #REQUIRED>
<!ATTLIST result type CDATA #REQUIRED>
<!ELEMENT summaryresult EMPTY>
<!ATTLIST summaryresult project CDATA #REQUIRED>
<!ATTLIST summaryresult module CDATA #REQUIRED>
<!ATTLIST summaryresult date CDATA #REQUIRED>
<!ATTLIST summaryresult statvalue CDATA #REQUIRED>
<!ATTLIST summaryresult filecount CDATA #REQUIRED>
<!ATTLIST summaryresult type CDATA #REQUIRED>
]>
<qalab version="1.2">
    <summary>
        <summaryresult date="2006-08-08" filecount="7" module="default"
            project="default" statvalue="5" type="checkstyle"/>
        <summaryresult date="2006-08-08" filecount="2" module="default"
            project="default" statvalue="3" type="pmd"/>
        <summaryresult date="2006-08-08" filecount="1" module="default"
            project="default" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-08-08" filecount="6" module="default"
            project="default" statvalue="47" type="cobertura-line"/>
        <summaryresult date="2006-08-08" filecount="6" module="default"
            project="default" statvalue="57" type="cobertura-branch"/>
        <summaryresult date="2006-08-09" filecount="7" module="default"
            project="default" statvalue="5" type="checkstyle"/>
        <summaryresult date="2006-08-09" filecount="6" module="default"
            project="default" statvalue="86" type="cobertura-line"/>
        <summaryresult date="2006-08-09" filecount="6" module="default"
            project="default" statvalue="91" type="cobertura-branch"/>
        <summaryresult date="2006-08-10" filecount="7" module="default"
            project="default" statvalue="4" type="checkstyle"/>
        <summaryresult date="2006-08-10" filecount="6" module="default"
            project="default" statvalue="90" type="cobertura-line"/>
        <summaryresult date="2006-08-10" filecount="6" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-08-19" filecount="7" module="default"
            project="default" statvalue="1" type="checkstyle"/>
        <summaryresult date="2006-08-19" filecount="6" module="default"
            project="default" statvalue="91" type="cobertura-line"/>
        <summaryresult date="2006-08-19" filecount="6" module="default"
            project="default" statvalue="96" type="cobertura-branch"/>
        <summaryresult date="2006-08-20" filecount="7" module="default"
            project="default" statvalue="1" type="checkstyle"/>
        <summaryresult date="2006-08-20" filecount="6" module="default"
            project="default" statvalue="90" type="cobertura-line"/>
        <summaryresult date="2006-08-20" filecount="6" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-08-23" filecount="10" module="default"
            project="default" statvalue="25" type="checkstyle"/>
        <summaryresult date="2006-08-23" filecount="9" module="default"
            project="default" statvalue="74" type="cobertura-line"/>
        <summaryresult date="2006-08-23" filecount="9" module="default"
            project="default" statvalue="87" type="cobertura-branch"/>
        <summaryresult date="2006-08-24" filecount="10" module="default"
            project="default" statvalue="1" type="checkstyle"/>
        <summaryresult date="2006-08-24" filecount="9" module="default"
            project="default" statvalue="62" type="cobertura-line"/>
        <summaryresult date="2006-08-24" filecount="9" module="default"
            project="default" statvalue="65" type="cobertura-branch"/>
        <summaryresult date="2006-08-28" filecount="13" module="default"
            project="default" statvalue="3" type="checkstyle"/>
        <summaryresult date="2006-08-28" filecount="12" module="default"
            project="default" statvalue="60" type="cobertura-line"/>
        <summaryresult date="2006-08-28" filecount="12" module="default"
            project="default" statvalue="65" type="cobertura-branch"/>
        <summaryresult date="2006-09-02" filecount="13" module="default"
            project="default" statvalue="9" type="checkstyle"/>
        <summaryresult date="2006-09-02" filecount="12" module="default"
            project="default" statvalue="59" type="cobertura-line"/>
        <summaryresult date="2006-09-02" filecount="12" module="default"
            project="default" statvalue="61" type="cobertura-branch"/>
        <summaryresult date="2006-09-04" filecount="15" module="default"
            project="default" statvalue="12" type="checkstyle"/>
        <summaryresult date="2006-09-04" filecount="1" module="default"
            project="default" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-09-04" filecount="14" module="default"
            project="default" statvalue="61" type="cobertura-line"/>
        <summaryresult date="2006-09-04" filecount="14" module="default"
            project="default" statvalue="64" type="cobertura-branch"/>
        <summaryresult date="2006-09-05" filecount="16" module="default"
            project="default" statvalue="9" type="checkstyle"/>
        <summaryresult date="2006-09-05" filecount="1" module="default"
            project="default" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-09-05" filecount="15" module="default"
            project="default" statvalue="63" type="cobertura-line"/>
        <summaryresult date="2006-09-05" filecount="15" module="default"
            project="default" statvalue="67" type="cobertura-branch"/>
        <summaryresult date="2006-09-06" filecount="18" module="default"
            project="default" statvalue="1" type="checkstyle"/>
        <summaryresult date="2006-09-06" filecount="17" module="default"
            project="default" statvalue="66" type="cobertura-line"/>
        <summaryresult date="2006-09-06" filecount="17" module="default"
            project="default" statvalue="68" type="cobertura-branch"/>
        <summaryresult date="2006-09-07" filecount="17" module="default"
            project="default" statvalue="64" type="cobertura-line"/>
        <summaryresult date="2006-09-07" filecount="17" module="default"
            project="default" statvalue="64" type="cobertura-branch"/>
        <summaryresult date="2006-09-09" filecount="17" module="default"
            project="default" statvalue="63" type="cobertura-line"/>
        <summaryresult date="2006-09-09" filecount="17" module="default"
            project="default" statvalue="64" type="cobertura-branch"/>
        <summaryresult date="2006-09-12" filecount="17" module="default"
            project="default" statvalue="59" type="cobertura-line"/>
        <summaryresult date="2006-09-12" filecount="17" module="default"
            project="default" statvalue="62" type="cobertura-branch"/>
        <summaryresult date="2006-09-14" filecount="17" module="default"
            project="default" statvalue="57" type="cobertura-line"/>
        <summaryresult date="2006-09-14" filecount="17" module="default"
            project="default" statvalue="60" type="cobertura-branch"/>
        <summaryresult date="2006-09-18" filecount="17" module="default"
            project="default" statvalue="57" type="cobertura-line"/>
        <summaryresult date="2006-09-18" filecount="17" module="default"
            project="default" statvalue="60" type="cobertura-branch"/>
        <summaryresult date="2006-09-20" filecount="17" module="default"
            project="default" statvalue="57" type="cobertura-line"/>
        <summaryresult date="2006-09-20" filecount="17" module="default"
            project="default" statvalue="60" type="cobertura-branch"/>
        <summaryresult date="2006-09-21" filecount="17" module="default"
            project="default" statvalue="57" type="cobertura-line"/>
        <summaryresult date="2006-09-21" filecount="17" module="default"
            project="default" statvalue="60" type="cobertura-branch"/>
        <summaryresult date="2006-09-22" filecount="17" module="default"
            project="default" statvalue="57" type="cobertura-line"/>
        <summaryresult date="2006-09-22" filecount="17" module="default"
            project="default" statvalue="60" type="cobertura-branch"/>
        <summaryresult date="2006-10-10" filecount="17" module="default"
            project="default" statvalue="58" type="cobertura-line"/>
        <summaryresult date="2006-10-10" filecount="17" module="default"
            project="default" statvalue="60" type="cobertura-branch"/>
        <summaryresult date="2006-10-11" filecount="17" module="default"
            project="default" statvalue="58" type="cobertura-line"/>
        <summaryresult date="2006-10-11" filecount="17" module="default"
            project="default" statvalue="60" type="cobertura-branch"/>
        <summaryresult date="2006-10-12" filecount="17" module="default"
            project="default" statvalue="58" type="cobertura-line"/>
        <summaryresult date="2006-10-12" filecount="17" module="default"
            project="default" statvalue="60" type="cobertura-branch"/>
        <summaryresult date="2006-10-13" filecount="17" module="default"
            project="default" statvalue="58" type="cobertura-line"/>
        <summaryresult date="2006-10-13" filecount="17" module="default"
            project="default" statvalue="60" type="cobertura-branch"/>
        <summaryresult date="2006-10-14" filecount="17" module="default"
            project="default" statvalue="58" type="cobertura-line"/>
        <summaryresult date="2006-10-14" filecount="17" module="default"
            project="default" statvalue="60" type="cobertura-branch"/>
        <summaryresult date="2006-10-15" filecount="17" module="default"
            project="default" statvalue="58" type="cobertura-line"/>
        <summaryresult date="2006-10-15" filecount="17" module="default"
            project="default" statvalue="60" type="cobertura-branch"/>
        <summaryresult date="2006-11-13" filecount="17" module="default"
            project="default" statvalue="56" type="cobertura-line"/>
        <summaryresult date="2006-11-13" filecount="17" module="default"
            project="default" statvalue="60" type="cobertura-branch"/>
        <summaryresult date="2007-01-03" filecount="19" module="default"
            project="default" statvalue="54" type="cobertura-line"/>
        <summaryresult date="2007-01-03" filecount="19" module="default"
            project="default" statvalue="58" type="cobertura-branch"/>
    </summary>
    <file
        id="default-default-net_objectlab_kit_datecalc_common_package.html"
        module="default"
        path="net/objectlab/kit/datecalc/common/package.html" project="default">
        <result date="2006-08-08" statvalue="1" type="checkstyle"/>
        <result date="2006-08-09" statvalue="1" type="checkstyle"/>
        <result date="2006-08-10" statvalue="1" type="checkstyle"/>
        <result date="2006-08-19" statvalue="1" type="checkstyle"/>
        <result date="2006-08-20" statvalue="1" type="checkstyle"/>
        <result date="2006-08-23" statvalue="1" type="checkstyle"/>
        <result date="2006-08-24" statvalue="1" type="checkstyle"/>
        <result date="2006-08-28" statvalue="1" type="checkstyle"/>
        <result date="2006-09-02" statvalue="1" type="checkstyle"/>
        <result date="2006-09-04" statvalue="1" type="checkstyle"/>
        <result date="2006-09-05" statvalue="1" type="checkstyle"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_common_Tenor.java"
        module="default"
        path="net/objectlab/kit/datecalc/common/Tenor.java" project="default">
        <result date="2006-08-08" statvalue="1" type="checkstyle"/>
        <result date="2006-08-08" statvalue="55" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="43" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="1" type="checkstyle"/>
        <result date="2006-08-09" statvalue="94" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="93" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="1" type="checkstyle"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-07" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-07" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-12" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-12" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-14" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-18" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-21" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-21" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-22" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-22" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-11" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-11" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-12" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-12" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-13" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-13" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-14" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-15" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-13" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-13" statvalue="100" type="cobertura-branch"/>
        <result date="2007-01-03" statvalue="100" type="cobertura-line"/>
        <result date="2007-01-03" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_common_WorkingWeek.java"
        module="default"
        path="net/objectlab/kit/datecalc/common/WorkingWeek.java" project="default">
        <result date="2006-08-08" statvalue="3" type="checkstyle"/>
        <result date="2006-08-08" statvalue="1" type="findbugs"/>
        <result date="2006-08-08" statvalue="82" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="3" type="checkstyle"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="2" type="checkstyle"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-04" statvalue="1" type="checkstyle"/>
        <result date="2006-09-04" statvalue="1" type="findbugs"/>
        <result date="2006-09-04" statvalue="95" type="cobertura-line"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-05" statvalue="1" type="checkstyle"/>
        <result date="2006-09-05" statvalue="1" type="findbugs"/>
        <result date="2006-09-05" statvalue="95" type="cobertura-line"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-06" statvalue="95" type="cobertura-line"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-07" statvalue="95" type="cobertura-line"/>
        <result date="2006-09-07" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-09" statvalue="95" type="cobertura-line"/>
        <result date="2006-09-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-12" statvalue="95" type="cobertura-line"/>
        <result date="2006-09-12" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-14" statvalue="95" type="cobertura-line"/>
        <result date="2006-09-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-18" statvalue="95" type="cobertura-line"/>
        <result date="2006-09-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-20" statvalue="95" type="cobertura-line"/>
        <result date="2006-09-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-21" statvalue="95" type="cobertura-line"/>
        <result date="2006-09-21" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-22" statvalue="95" type="cobertura-line"/>
        <result date="2006-09-22" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-10" statvalue="94" type="cobertura-line"/>
        <result date="2006-10-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-11" statvalue="94" type="cobertura-line"/>
        <result date="2006-10-11" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-12" statvalue="94" type="cobertura-line"/>
        <result date="2006-10-12" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-13" statvalue="94" type="cobertura-line"/>
        <result date="2006-10-13" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-14" statvalue="94" type="cobertura-line"/>
        <result date="2006-10-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-15" statvalue="94" type="cobertura-line"/>
        <result date="2006-10-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-13" statvalue="95" type="cobertura-line"/>
        <result date="2006-11-13" statvalue="100" type="cobertura-branch"/>
        <result date="2007-01-03" statvalue="95" type="cobertura-line"/>
        <result date="2007-01-03" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_common_TenorCode.java"
        module="default"
        path="net/objectlab/kit/datecalc/common/TenorCode.java" project="default">
        <result date="2006-08-08" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-07" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-07" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-12" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-12" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-14" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-18" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-21" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-21" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-22" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-22" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-11" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-11" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-12" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-12" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-13" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-13" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-14" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-15" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-13" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-13" statvalue="100" type="cobertura-branch"/>
        <result date="2007-01-03" statvalue="100" type="cobertura-line"/>
        <result date="2007-01-03" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_common_HolidayHandlerType.java"
        module="default"
        path="net/objectlab/kit/datecalc/common/HolidayHandlerType.java" project="default">
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-07" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-12" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-21" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-22" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-11" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-12" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-13" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-13" statvalue="100" type="cobertura-branch"/>
        <result date="2007-01-03" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_common_PeriodCountBasis.java"
        module="default"
        path="net/objectlab/kit/datecalc/common/PeriodCountBasis.java" project="default">
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-07" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-12" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-21" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-22" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-10" statvalue="100" type="cobertura-branch"/>