<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE qalab [<!ELEMENT qalab (summary,file*)>
<!ATTLIST qalab version CDATA #REQUIRED>
<!ELEMENT summary (summaryresult*)>
<!ELEMENT file (result+)>
<!ATTLIST file id ID #REQUIRED>
<!ATTLIST file project CDATA #REQUIRED>
<!ATTLIST file module CDATA #REQUIRED>
<!ATTLIST file path CDATA #REQUIRED>
<!ELEMENT result EMPTY>
<!ATTLIST result date CDATA #REQUIRED>
<!ATTLIST result statvalue CDATA #REQUIRED>
<!ATTLIST result type CDATA #REQUIRED>
<!ELEMENT summaryresult EMPTY>
<!ATTLIST summaryresult project CDATA #REQUIRED>
<!ATTLIST summaryresult module CDATA #REQUIRED>
<!ATTLIST summaryresult date CDATA #REQUIRED>
<!ATTLIST summaryresult statvalue CDATA #REQUIRED>
<!ATTLIST summaryresult filecount CDATA #REQUIRED>
<!ATTLIST summaryresult type CDATA #REQUIRED>
]>
<qalab version="1.2">
    <summary>
        <summaryresult date="2006-08-08" filecount="8" module="default"
            project="default" statvalue="3" type="checkstyle"/>
        <summaryresult date="2006-08-08" filecount="2" module="default"
            project="default" statvalue="7" type="pmd"/>
        <summaryresult date="2006-08-08" filecount="1" module="default"
            project="default" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-08-09" filecount="8" module="default"
            project="default" statvalue="3" type="checkstyle"/>
        <summaryresult date="2006-08-09" filecount="2" module="default"
            project="default" statvalue="7" type="pmd"/>
        <summaryresult date="2006-08-09" filecount="1" module="default"
            project="default" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-08-10" filecount="8" module="default"
            project="default" statvalue="3" type="checkstyle"/>
        <summaryresult date="2006-08-10" filecount="2" module="default"
            project="default" statvalue="7" type="pmd"/>
        <summaryresult date="2006-08-10" filecount="1" module="default"
            project="default" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-08-20" filecount="10" module="default"
            project="default" statvalue="10" type="checkstyle"/>
        <summaryresult date="2006-08-20" filecount="1" module="default"
            project="default" statvalue="1" type="pmd"/>
        <summaryresult date="2006-08-20" filecount="1" module="default"
            project="default" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-08-20" filecount="9" module="default"
            project="default" statvalue="77" type="cobertura-line"/>
        <summaryresult date="2006-08-20" filecount="9" module="default"
            project="default" statvalue="77" type="cobertura-branch"/>
        <summaryresult date="2006-08-23" filecount="8" module="default"
            project="default" statvalue="8" type="checkstyle"/>
        <summaryresult date="2006-08-23" filecount="1" module="default"
            project="default" statvalue="1" type="pmd"/>
        <summaryresult date="2006-08-23" filecount="7" module="default"
            project="default" statvalue="81" type="cobertura-line"/>
        <summaryresult date="2006-08-23" filecount="7" module="default"
            project="default" statvalue="79" type="cobertura-branch"/>
        <summaryresult date="2006-08-24" filecount="8" module="default"
            project="default" statvalue="6" type="checkstyle"/>
        <summaryresult date="2006-08-24" filecount="1" module="default"
            project="default" statvalue="1" type="pmd"/>
        <summaryresult date="2006-08-24" filecount="7" module="default"
            project="default" statvalue="86" type="cobertura-line"/>
        <summaryresult date="2006-08-24" filecount="7" module="default"
            project="default" statvalue="81" type="cobertura-branch"/>
        <summaryresult date="2006-08-28" filecount="9" module="default"
            project="default" statvalue="5" type="checkstyle"/>
        <summaryresult date="2006-08-28" filecount="1" module="default"
            project="default" statvalue="1" type="pmd"/>
        <summaryresult date="2006-08-28" filecount="1" module="default"
            project="default" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-08-28" filecount="8" module="default"
            project="default" statvalue="71" type="cobertura-line"/>
        <summaryresult date="2006-08-28" filecount="8" module="default"
            project="default" statvalue="71" type="cobertura-branch"/>
        <summaryresult date="2006-09-02" filecount="11" module="default"
            project="default" statvalue="20" type="checkstyle"/>
        <summaryresult date="2006-09-02" filecount="1" module="default"
            project="default" statvalue="1" type="pmd"/>
        <summaryresult date="2006-09-02" filecount="1" module="default"
            project="default" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-09-02" filecount="10" module="default"
            project="default" statvalue="68" type="cobertura-line"/>
        <summaryresult date="2006-09-02" filecount="10" module="default"
            project="default" statvalue="71" type="cobertura-branch"/>
        <summaryresult date="2006-09-04" filecount="17" module="default"
            project="default" statvalue="18" type="checkstyle"/>
        <summaryresult date="2006-09-04" filecount="16" module="default"
            project="default" statvalue="77" type="cobertura-line"/>
        <summaryresult date="2006-09-04" filecount="16" module="default"
            project="default" statvalue="79" type="cobertura-branch"/>
        <summaryresult date="2006-09-05" filecount="16" module="default"
            project="default" statvalue="14" type="checkstyle"/>
        <summaryresult date="2006-09-05" filecount="15" module="default"
            project="default" statvalue="83" type="cobertura-line"/>
        <summaryresult date="2006-09-05" filecount="15" module="default"
            project="default" statvalue="87" type="cobertura-branch"/>
        <summaryresult date="2006-09-06" filecount="2" module="default"
            project="default" statvalue="32" type="simian"/>
        <summaryresult date="2006-09-06" filecount="21" module="default"
            project="default" statvalue="84" type="cobertura-line"/>
        <summaryresult date="2006-09-06" filecount="21" module="default"
            project="default" statvalue="89" type="cobertura-branch"/>
        <summaryresult date="2006-09-07" filecount="19" module="default"
            project="default" statvalue="93" type="cobertura-line"/>
        <summaryresult date="2006-09-07" filecount="19" module="default"
            project="default" statvalue="92" type="cobertura-branch"/>
        <summaryresult date="2006-09-09" filecount="17" module="default"
            project="default" statvalue="95" type="cobertura-line"/>
        <summaryresult date="2006-09-09" filecount="17" module="default"
            project="default" statvalue="95" type="cobertura-branch"/>
        <summaryresult date="2006-09-12" filecount="18" module="default"
            project="default" statvalue="6" type="checkstyle"/>
        <summaryresult date="2006-09-12" filecount="6" module="default"
            project="default" statvalue="6" type="pmd"/>
        <summaryresult date="2006-09-12" filecount="17" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2006-09-12" filecount="17" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-09-14" filecount="17" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2006-09-14" filecount="17" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-09-18" filecount="17" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2006-09-18" filecount="17" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-09-20" filecount="17" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2006-09-20" filecount="17" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-09-21" filecount="17" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2006-09-21" filecount="17" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-09-22" filecount="17" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2006-09-22" filecount="17" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-10-10" filecount="17" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2006-10-10" filecount="17" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-10-11" filecount="17" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2006-10-11" filecount="17" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-10-12" filecount="17" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2006-10-12" filecount="17" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-10-13" filecount="17" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2006-10-13" filecount="17" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-10-14" filecount="17" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2006-10-14" filecount="17" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-10-15" filecount="17" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2006-10-15" filecount="17" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-11-13" filecount="19" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2006-11-13" filecount="19" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2007-01-03" filecount="19" module="default"
            project="default" statvalue="99" type="cobertura-line"/>
        <summaryresult date="2007-01-03" filecount="19" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
    </summary>
    <file
        id="default-default-net_objectlab_kit_datecalc_jdk_package.html"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/package.html" project="default">
        <result date="2006-08-08" statvalue="1" type="checkstyle"/>
        <result date="2006-08-09" statvalue="1" type="checkstyle"/>
        <result date="2006-08-10" statvalue="1" type="checkstyle"/>
        <result date="2006-08-20" statvalue="1" type="checkstyle"/>
        <result date="2006-08-23" statvalue="1" type="checkstyle"/>
        <result date="2006-08-24" statvalue="1" type="checkstyle"/>
        <result date="2006-08-28" statvalue="1" type="checkstyle"/>
        <result date="2006-09-02" statvalue="1" type="checkstyle"/>
        <result date="2006-09-04" statvalue="1" type="checkstyle"/>
        <result date="2006-09-05" statvalue="1" type="checkstyle"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_jdk_BaseDateCalculator.java"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/BaseDateCalculator.java" project="default">
        <result date="2006-08-08" statvalue="1" type="checkstyle"/>
        <result date="2006-08-08" statvalue="4" type="pmd"/>
        <result date="2006-08-08" statvalue="1" type="findbugs"/>
        <result date="2006-08-09" statvalue="1" type="checkstyle"/>
        <result date="2006-08-09" statvalue="4" type="pmd"/>
        <result date="2006-08-09" statvalue="1" type="findbugs"/>
        <result date="2006-08-10" statvalue="1" type="checkstyle"/>
        <result date="2006-08-10" statvalue="4" type="pmd"/>
        <result date="2006-08-10" statvalue="1" type="findbugs"/>
        <result date="2006-08-20" statvalue="7" type="checkstyle"/>
        <result date="2006-08-20" statvalue="1" type="pmd"/>
        <result date="2006-08-20" statvalue="1" type="findbugs"/>
        <result date="2006-08-20" statvalue="74" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="75" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="5" type="checkstyle"/>
        <result date="2006-08-23" statvalue="1" type="pmd"/>
        <result date="2006-08-23" statvalue="78" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="76" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="3" type="checkstyle"/>
        <result date="2006-08-24" statvalue="1" type="pmd"/>
        <result date="2006-08-24" statvalue="84" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="76" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="3" type="checkstyle"/>
        <result date="2006-08-28" statvalue="1" type="pmd"/>
        <result date="2006-08-28" statvalue="84" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="76" type="cobertura-branch"/>
        <result date="2006-09-02" statvalue="4" type="checkstyle"/>
        <result date="2006-09-02" statvalue="1" type="pmd"/>
        <result date="2006-09-02" statvalue="84" type="cobertura-line"/>
        <result date="2006-09-02" statvalue="75" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_jdk_DefaultDateCalculatorFactory.java"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/DefaultDateCalculatorFactory.java" project="default">
        <result date="2006-08-08" statvalue="1" type="checkstyle"/>
        <result date="2006-08-09" statvalue="1" type="checkstyle"/>
        <result date="2006-08-10" statvalue="1" type="checkstyle"/>
        <result date="2006-08-20" statvalue="1" type="checkstyle"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="1" type="checkstyle"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="1" type="checkstyle"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="1" type="findbugs"/>
        <result date="2006-08-28" statvalue="80" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="80" type="cobertura-branch"/>
        <result date="2006-09-02" statvalue="1" type="findbugs"/>
        <result date="2006-09-02" statvalue="95" type="cobertura-line"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-C:_project_objectlab-kit_datecalc-jdk_src_test_java_net_objectlab_kit_datecalc_jdk_DateCalculatorCombinationTest.java"
        module="default"
        path="C:/project/objectlab-kit/datecalc-jdk/src/test/java/net/objectlab/kit/datecalc/jdk/DateCalculatorCombinationTest.java" project="default">
        <result date="2006-08-08" statvalue="3" type="pmd"/>
        <result date="2006-08-09" statvalue="3" type="pmd"/>
        <result date="2006-08-10" statvalue="3" type="pmd"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_jdk_DateCalculator.java"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/DateCalculator.java" project="default">
        <result date="2006-08-08" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_jdk_DateCalculatorFactory.java"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/DateCalculatorFactory.java" project="default">
        <result date="2006-08-08" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_jdk_HolidayHandler.java"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/HolidayHandler.java" project="default">
        <result date="2006-08-08" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_jdk_PeriodCountCalculator.java"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/PeriodCountCalculator.java" project="default">
        <result date="2006-08-08" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_jdk_DefaultPeriodCountCalculator.java"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/DefaultPeriodCountCalculator.java" project="default">
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="50" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="50" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="50" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="50" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-C:_project_objectlabkit_datecalc-jdk_src_test_java_net_objectlab_kit_datecalc_jdk_DateCalculatorCombinationTest.java"
        module="default"
        path="C:/project/objectlabkit/datecalc-jdk/src/test/java/net/objectlab/kit/datecalc/jdk/DateCalculatorCombinationTest.java" project="default"/>
    <file id="default-default-net_objectlab_kit_datecalc_jdk_Utils.java"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/Utils.java" project="default">
        <result date="2006-08-20" statvalue="1" type="checkstyle"/>
        <result date="2006-08-20" statvalue="75" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="1" type="checkstyle"/>
        <result date="2006-08-23" statvalue="75" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="1" type="checkstyle"/>
        <result date="2006-08-24" statvalue="75" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="1" type="checkstyle"/>
        <result date="2006-08-28" statvalue="75" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-02" statvalue="1" type="checkstyle"/>
        <result date="2006-09-02" statvalue="75" type="cobertura-line"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_jdk_ForwardHandler.java"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/ForwardHandler.java" project="default">
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_jdk_BackwardHandler.java"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/BackwardHandler.java" project="default">
        <result date="2006-08-28" statvalue="66" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-02" statvalue="66" type="cobertura-line"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_jdk_ModifiedPreceedingHandler.java"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/ModifiedPreceedingHandler.java" project="default">
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-02" statvalue="66" type="cobertura-line"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_jdk_CalendarPeriodCountCalculator.java"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/CalendarPeriodCountCalculator.java" project="default">
        <result date="2006-09-02" statvalue="9" type="checkstyle"/>
        <result date="2006-09-02" statvalue="67" type="cobertura-line"/>
        <result date="2006-09-02" statvalue="84" type="cobertura-branch"/>
        <result date="2006-09-04" statvalue="79" type="cobertura-line"/>
        <result date="2006-09-04" statvalue="84" type="cobertura-branch"/>
        <result date="2006-09-05" statvalue="79" type="cobertura-line"/>
        <result date="2006-09-05" statvalue="84" type="cobertura-branch"/>
        <result date="2006-09-06" statvalue="79" type="cobertura-line"/>
        <result date="2006-09-06" statvalue="84" type="cobertura-branch"/>
        <result date="2006-09-07" statvalue="79" type="cobertura-line"/>
        <result date="2006-09-07" statvalue="84" type="cobertura-branch"/>
        <result date="2006-09-09" statvalue="79" type="cobertura-line"/>
        <result date="2006-09-09" statvalue="84" type="cobertura-branch"/>
        <result date="2006-09-12" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-12" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-14" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-18" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-21" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-21" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-22" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-22" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-11" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-11" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-12" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-12" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-13" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-13" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-14" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-15" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-13" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-13" statvalue="100" type="cobertura-branch"/>
        <result date="2007-01-03" statvalue="100" type="cobertura-line"/>
        <result date="2007-01-03" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_jdk_DatePeriodCountCalculator.java"
        module="default"
        path="net/objectlab/kit/datecalc/jdk/DatePeriodCountCalculator.java" project="default">
        <result date="2006-09-02" statvalue="1" type="checkstyle"/>