<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE qalab [<!ELEMENT qalab (summary,file*)>
<!ATTLIST qalab version CDATA #REQUIRED>
<!ELEMENT summary (summaryresult*)>
<!ELEMENT file (result+)>
<!ATTLIST file id ID #REQUIRED>
<!ATTLIST file project CDATA #REQUIRED>
<!ATTLIST file module CDATA #REQUIRED>
<!ATTLIST file path CDATA #REQUIRED>
<!ELEMENT result EMPTY>
<!ATTLIST result date CDATA #REQUIRED>
<!ATTLIST result statvalue CDATA #REQUIRED>
<!ATTLIST result type CDATA #REQUIRED>
<!ELEMENT summaryresult EMPTY>
<!ATTLIST summaryresult project CDATA #REQUIRED>
<!ATTLIST summaryresult module CDATA #REQUIRED>
<!ATTLIST summaryresult date CDATA #REQUIRED>
<!ATTLIST summaryresult statvalue CDATA #REQUIRED>
<!ATTLIST summaryresult filecount CDATA #REQUIRED>
<!ATTLIST summaryresult type CDATA #REQUIRED>
]>
<qalab version="1.2">
    <summary>
        <summaryresult date="2006-08-08" filecount="13" module="default"
            project="default" statvalue="43" type="checkstyle"/>
        <summaryresult date="2006-08-08" filecount="6" module="default"
            project="default" statvalue="15" type="pmd"/>
        <summaryresult date="2006-08-08" filecount="2" module="default"
            project="default" statvalue="2" type="findbugs"/>
        <summaryresult date="2006-08-08" filecount="12" module="default"
            project="default" statvalue="69" type="cobertura-line"/>
        <summaryresult date="2006-08-08" filecount="12" module="default"
            project="default" statvalue="72" type="cobertura-branch"/>
        <summaryresult date="2006-08-09" filecount="13" module="default"
            project="default" statvalue="45" type="checkstyle"/>
        <summaryresult date="2006-08-09" filecount="6" module="default"
            project="default" statvalue="18" type="pmd"/>
        <summaryresult date="2006-08-09" filecount="2" module="default"
            project="default" statvalue="2" type="findbugs"/>
        <summaryresult date="2006-08-09" filecount="12" module="default"
            project="default" statvalue="73" type="cobertura-line"/>
        <summaryresult date="2006-08-09" filecount="12" module="default"
            project="default" statvalue="76" type="cobertura-branch"/>
        <summaryresult date="2006-08-10" filecount="13" module="default"
            project="default" statvalue="34" type="checkstyle"/>
        <summaryresult date="2006-08-10" filecount="3" module="default"
            project="default" statvalue="6" type="pmd"/>
        <summaryresult date="2006-08-10" filecount="2" module="default"
            project="default" statvalue="2" type="findbugs"/>
        <summaryresult date="2006-08-10" filecount="12" module="default"
            project="default" statvalue="84" type="cobertura-line"/>
        <summaryresult date="2006-08-10" filecount="12" module="default"
            project="default" statvalue="86" type="cobertura-branch"/>
        <summaryresult date="2006-08-19" filecount="13" module="default"
            project="default" statvalue="1" type="checkstyle"/>
        <summaryresult date="2006-08-19" filecount="3" module="default"
            project="default" statvalue="6" type="pmd"/>
        <summaryresult date="2006-08-19" filecount="12" module="default"
            project="default" statvalue="89" type="cobertura-line"/>
        <summaryresult date="2006-08-19" filecount="12" module="default"
            project="default" statvalue="92" type="cobertura-branch"/>
        <summaryresult date="2006-08-20" filecount="13" module="default"
            project="default" statvalue="2" type="checkstyle"/>
        <summaryresult date="2006-08-20" filecount="1" module="default"
            project="default" statvalue="1" type="pmd"/>
        <summaryresult date="2006-08-20" filecount="12" module="default"
            project="default" statvalue="86" type="cobertura-line"/>
        <summaryresult date="2006-08-20" filecount="12" module="default"
            project="default" statvalue="88" type="cobertura-branch"/>
        <summaryresult date="2006-08-23" filecount="11" module="default"
            project="default" statvalue="1" type="checkstyle"/>
        <summaryresult date="2006-08-23" filecount="10" module="default"
            project="default" statvalue="93" type="cobertura-line"/>
        <summaryresult date="2006-08-23" filecount="10" module="default"
            project="default" statvalue="95" type="cobertura-branch"/>
        <summaryresult date="2006-08-24" filecount="10" module="default"
            project="default" statvalue="93" type="cobertura-line"/>
        <summaryresult date="2006-08-24" filecount="10" module="default"
            project="default" statvalue="94" type="cobertura-branch"/>
        <summaryresult date="2006-08-28" filecount="1" module="default"
            project="default" statvalue="1" type="findbugs"/>
        <summaryresult date="2006-08-28" filecount="8" module="default"
            project="default" statvalue="93" type="cobertura-line"/>
        <summaryresult date="2006-08-28" filecount="8" module="default"
            project="default" statvalue="94" type="cobertura-branch"/>
        <summaryresult date="2006-09-02" filecount="18" module="default"
            project="default" statvalue="4" type="checkstyle"/>
        <summaryresult date="2006-09-02" filecount="4" module="default"
            project="default" statvalue="40" type="simian"/>
        <summaryresult date="2006-09-02" filecount="17" module="default"
            project="default" statvalue="86" type="cobertura-line"/>
        <summaryresult date="2006-09-02" filecount="17" module="default"
            project="default" statvalue="88" type="cobertura-branch"/>
        <summaryresult date="2006-09-04" filecount="18" module="default"
            project="default" statvalue="10" type="checkstyle"/>
        <summaryresult date="2006-09-04" filecount="4" module="default"
            project="default" statvalue="40" type="simian"/>
        <summaryresult date="2006-09-04" filecount="17" module="default"
            project="default" statvalue="84" type="cobertura-line"/>
        <summaryresult date="2006-09-04" filecount="17" module="default"
            project="default" statvalue="87" type="cobertura-branch"/>
        <summaryresult date="2006-09-05" filecount="4" module="default"
            project="default" statvalue="40" type="simian"/>
        <summaryresult date="2006-09-05" filecount="17" module="default"
            project="default" statvalue="91" type="cobertura-line"/>
        <summaryresult date="2006-09-05" filecount="17" module="default"
            project="default" statvalue="93" type="cobertura-branch"/>
        <summaryresult date="2006-09-06" filecount="19" module="default"
            project="default" statvalue="95" type="cobertura-line"/>
        <summaryresult date="2006-09-06" filecount="19" module="default"
            project="default" statvalue="96" type="cobertura-branch"/>
        <summaryresult date="2006-09-07" filecount="19" module="default"
            project="default" statvalue="94" type="cobertura-line"/>
        <summaryresult date="2006-09-07" filecount="19" module="default"
            project="default" statvalue="93" type="cobertura-branch"/>
        <summaryresult date="2006-09-09" filecount="19" module="default"
            project="default" statvalue="96" type="cobertura-line"/>
        <summaryresult date="2006-09-09" filecount="19" module="default"
            project="default" statvalue="96" type="cobertura-branch"/>
        <summaryresult date="2006-09-12" filecount="20" module="default"
            project="default" statvalue="2" type="checkstyle"/>
        <summaryresult date="2006-09-12" filecount="2" module="default"
            project="default" statvalue="2" type="pmd"/>
        <summaryresult date="2006-09-12" filecount="19" module="default"
            project="default" statvalue="98" type="cobertura-line"/>
        <summaryresult date="2006-09-12" filecount="19" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-09-14" filecount="19" module="default"
            project="default" statvalue="98" type="cobertura-line"/>
        <summaryresult date="2006-09-14" filecount="19" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-09-18" filecount="19" module="default"
            project="default" statvalue="98" type="cobertura-line"/>
        <summaryresult date="2006-09-18" filecount="19" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-09-20" filecount="19" module="default"
            project="default" statvalue="98" type="cobertura-line"/>
        <summaryresult date="2006-09-20" filecount="19" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-09-21" filecount="19" module="default"
            project="default" statvalue="98" type="cobertura-line"/>
        <summaryresult date="2006-09-21" filecount="19" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-09-22" filecount="19" module="default"
            project="default" statvalue="98" type="cobertura-line"/>
        <summaryresult date="2006-09-22" filecount="19" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-10-10" filecount="19" module="default"
            project="default" statvalue="98" type="cobertura-line"/>
        <summaryresult date="2006-10-10" filecount="19" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-10-12" filecount="19" module="default"
            project="default" statvalue="98" type="cobertura-line"/>
        <summaryresult date="2006-10-12" filecount="19" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-10-13" filecount="19" module="default"
            project="default" statvalue="98" type="cobertura-line"/>
        <summaryresult date="2006-10-13" filecount="19" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-10-14" filecount="19" module="default"
            project="default" statvalue="98" type="cobertura-line"/>
        <summaryresult date="2006-10-14" filecount="19" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-10-15" filecount="19" module="default"
            project="default" statvalue="98" type="cobertura-line"/>
        <summaryresult date="2006-10-15" filecount="19" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2006-11-13" filecount="22" module="default"
            project="default" statvalue="2" type="checkstyle"/>
        <summaryresult date="2006-11-13" filecount="21" module="default"
            project="default" statvalue="98" type="cobertura-line"/>
        <summaryresult date="2006-11-13" filecount="21" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2007-01-03" filecount="22" module="default"
            project="default" statvalue="2" type="checkstyle"/>
        <summaryresult date="2007-01-03" filecount="21" module="default"
            project="default" statvalue="98" type="cobertura-line"/>
        <summaryresult date="2007-01-03" filecount="21" module="default"
            project="default" statvalue="100" type="cobertura-branch"/>
    </summary>
    <file
        id="default-default-net_objectlab_kit_datecalc_joda_package.html"
        module="default"
        path="net/objectlab/kit/datecalc/joda/package.html" project="default">
        <result date="2006-08-08" statvalue="1" type="checkstyle"/>
        <result date="2006-08-09" statvalue="1" type="checkstyle"/>
        <result date="2006-08-10" statvalue="1" type="checkstyle"/>
        <result date="2006-08-19" statvalue="1" type="checkstyle"/>
        <result date="2006-08-20" statvalue="1" type="checkstyle"/>
        <result date="2006-08-23" statvalue="1" type="checkstyle"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_joda_BaseDateCalculator.java"
        module="default"
        path="net/objectlab/kit/datecalc/joda/BaseDateCalculator.java" project="default">
        <result date="2006-08-08" statvalue="9" type="checkstyle"/>
        <result date="2006-08-08" statvalue="1" type="findbugs"/>
        <result date="2006-08-08" statvalue="79" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="73" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="9" type="checkstyle"/>
        <result date="2006-08-09" statvalue="1" type="findbugs"/>
        <result date="2006-08-09" statvalue="79" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="75" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="8" type="checkstyle"/>
        <result date="2006-08-10" statvalue="1" type="findbugs"/>
        <result date="2006-08-10" statvalue="97" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-19" statvalue="98" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="1" type="checkstyle"/>
        <result date="2006-08-20" statvalue="1" type="pmd"/>
        <result date="2006-08-20" statvalue="97" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="97" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_joda_DefaultDateCalculatorFactory.java"
        module="default"
        path="net/objectlab/kit/datecalc/joda/DefaultDateCalculatorFactory.java" project="default">
        <result date="2006-08-08" statvalue="1" type="checkstyle"/>
        <result date="2006-08-08" statvalue="85" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="80" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="1" type="checkstyle"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="1" type="checkstyle"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="1" type="findbugs"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_joda_DefaultPeriodCountCalculator.java"
        module="default"
        path="net/objectlab/kit/datecalc/joda/DefaultPeriodCountCalculator.java" project="default">
        <result date="2006-08-08" statvalue="31" type="checkstyle"/>
        <result date="2006-08-08" statvalue="1" type="findbugs"/>
        <result date="2006-08-08" statvalue="66" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="84" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="31" type="checkstyle"/>
        <result date="2006-08-09" statvalue="1" type="findbugs"/>
        <result date="2006-08-09" statvalue="69" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="92" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="22" type="checkstyle"/>
        <result date="2006-08-10" statvalue="1" type="findbugs"/>
        <result date="2006-08-10" statvalue="81" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="84" type="cobertura-branch"/>
        <result date="2006-08-19" statvalue="84" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="90" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="81" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="84" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="81" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="84" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="81" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="84" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="81" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="84" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_joda_JodaWorkingWeek.java"
        module="default"
        path="net/objectlab/kit/datecalc/joda/JodaWorkingWeek.java" project="default">
        <result date="2006-08-08" statvalue="1" type="checkstyle"/>
        <result date="2006-08-08" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="3" type="checkstyle"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="2" type="checkstyle"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-02" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-04" statvalue="2" type="checkstyle"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-04" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-05" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-06" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-07" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-07" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-12" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-12" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-14" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-18" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-18" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-21" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-21" statvalue="100" type="cobertura-branch"/>
        <result date="2006-09-22" statvalue="100" type="cobertura-line"/>
        <result date="2006-09-22" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-12" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-12" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-13" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-13" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-14" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-14" statvalue="100" type="cobertura-branch"/>
        <result date="2006-10-15" statvalue="100" type="cobertura-line"/>
        <result date="2006-10-15" statvalue="100" type="cobertura-branch"/>
        <result date="2006-11-13" statvalue="100" type="cobertura-line"/>
        <result date="2006-11-13" statvalue="100" type="cobertura-branch"/>
        <result date="2007-01-03" statvalue="100" type="cobertura-line"/>
        <result date="2007-01-03" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_joda_BackwardHandler.java"
        module="default"
        path="net/objectlab/kit/datecalc/joda/BackwardHandler.java" project="default">
        <result date="2006-08-08" statvalue="28" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="28" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="28" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="85" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_joda_DateCalculator.java"
        module="default"
        path="net/objectlab/kit/datecalc/joda/DateCalculator.java" project="default">
        <result date="2006-08-08" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_joda_DateCalculatorFactory.java"
        module="default"
        path="net/objectlab/kit/datecalc/joda/DateCalculatorFactory.java" project="default">
        <result date="2006-08-08" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_joda_ForwardHandler.java"
        module="default"
        path="net/objectlab/kit/datecalc/joda/ForwardHandler.java" project="default">
        <result date="2006-08-08" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-28" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_joda_HolidayHandler.java"
        module="default"
        path="net/objectlab/kit/datecalc/joda/HolidayHandler.java" project="default">
        <result date="2006-08-08" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_joda_PeriodCountCalculator.java"
        module="default"
        path="net/objectlab/kit/datecalc/joda/PeriodCountCalculator.java" project="default">
        <result date="2006-08-08" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-08" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-09" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-20" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-23" statvalue="100" type="cobertura-branch"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-line"/>
        <result date="2006-08-24" statvalue="100" type="cobertura-branch"/>
    </file>
    <file
        id="default-default-net_objectlab_kit_datecalc_joda_ModifiedFollowingHandler.java"
        module="default"
        path="net/objectlab/kit/datecalc/joda/ModifiedFollowingHandler.java" project="default">
        <result date="2006-08-09" statvalue="16" type="cobertura-line"/>
        <result date="2006-08-10" statvalue="16" type="cobertura-line"/>
        <result date="2006-08-19" statvalue="16" type="cobertura-line"/>